install:
    - # skip
language: go
matrix:
    allow_failures: ~
    include:
        - go: tip
script:
    - go get -t -v ./...
    - diff -u <(echo -n) <(gofmt -d .)
    - go vet $(go list ./...)
    - go test -v -race ./...
sudo: false
